// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $error from "./routes/error.tsx";
import * as $film_id_ from "./routes/film/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $MainIsland from "./islands/MainIsland.tsx";
import * as $filtro_NombreFilter from "./islands/filtro/NombreFilter.tsx";
import * as $filtro_SelectFilter from "./islands/filtro/SelectFilter.tsx";
import * as $modals_index_ButtonModal from "./islands/modals/index/ButtonModal.tsx";
import * as $modals_index_C_A_Modal from "./islands/modals/index/C_A_Modal.tsx";
import * as $modals_index_options_AddToProject from "./islands/modals/index/options/AddToProject.tsx";
import * as $modals_index_options_CreateProject from "./islands/modals/index/options/CreateProject.tsx";
import * as $modals_project_DeleteProject from "./islands/modals/project/DeleteProject.tsx";
import * as $modals_project_ModifyProject from "./islands/modals/project/ModifyProject.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/error.tsx": $error,
    "./routes/film/[id].tsx": $film_id_,
    "./routes/index.tsx": $index,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/MainIsland.tsx": $MainIsland,
    "./islands/filtro/NombreFilter.tsx": $filtro_NombreFilter,
    "./islands/filtro/SelectFilter.tsx": $filtro_SelectFilter,
    "./islands/modals/index/ButtonModal.tsx": $modals_index_ButtonModal,
    "./islands/modals/index/C_A_Modal.tsx": $modals_index_C_A_Modal,
    "./islands/modals/index/options/AddToProject.tsx":
      $modals_index_options_AddToProject,
    "./islands/modals/index/options/CreateProject.tsx":
      $modals_index_options_CreateProject,
    "./islands/modals/project/DeleteProject.tsx": $modals_project_DeleteProject,
    "./islands/modals/project/ModifyProject.tsx": $modals_project_ModifyProject,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
